apiVersion: apps/v1
kind: Deployment # type of resource
metadata:
  name: ms-a
  labels:
    app: ms-a

spec:
  replicas: 3
  selector:
    matchLabels:
      app: ms-a 
  template: 
    metadata:
      labels:
        app: ms-a
    spec:
      containers:
        - name: ms-a
          image: docker.io/laykidi/ms-a
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          env:
            - name: MSB_HOST
              value: "80"
            - name: MSB_PORT
              value: "3000"
