apiVersion: apps/v1

kind: Deployment # type of resource

metadata:
  namespace: ms-b-ns 
  name: ms-b
  labels:
    app: nginx

spec:
  replicas: 3
  selector:
    matchLabels:
      app:
        ms-b # all pods with with label will belong to the deployment,
        # if we create a pod manually with the
        # same label it will belong to the deployment
        #(and it will kill one of its pods
        # since the desired number is this case is )
  template: # template is the definition of the pod
    metadata:
      labels:
        app: ms-b
    spec:
      containers:
        - name: ms-b
          image: docker.io/laykidi/ms-b
          ports:
            - containerPort: 3000
